### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by xeroc** [xeroc/piston#50]
# piston.steem.Steem()

- [ ] implement `list_accounts` generator
- [ ] properly integrate `steemexchange.exchange` into `piston.steem.SteemExchange`

# piston.cli

- [ ] DEX calls (buy, sell, orderbook, etc.) - (requires more work on `piston.steem.SteemExchange`)

# piston.web

- [ ] implement page for transfers
- [ ] implement page for trading (requires more work on `piston.steem.SteemExchange`)
- [ ] some quasi realtime stats using a blockchain stream in a separate thread

# piston.offline
- [ ] piston offline signer:
  1. construct unsigned transaction skeleton (TaPOS parameters)
  2. sign the transaction on an offline computer
  3. broadcast again on online computer

**Comment by dskvr** [comment]
Where is `piston-offline`?
